INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 20);
INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 25);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bill' , 30);
INSERT INTO PERSON (NAME, AGE) VALUES ('Nancy', 40);
